version: '3.7'

services:
  db:
    image: postgres:13.1
    container_name: db-windy_coffee
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=user_windy_coffee
      - POSTGRES_DB=windy_coffee
      - POSTGRES_PASSWORD=QAERFHJFSHC12985
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./docker/db:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - 3015:5432