version: '3.7'
services:
  smile-home-backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      SQL_DATABASE_URL: 'postgresql+psycopg2://user_windy_coffee:QAERFHJFSHC12985@103.3.246.216:3015/windy_coffee_prod'
      SECRET_KEY: ${SECRET_KEY}
      TZ: 'Asia/Ho_Chi_Minh'
    ports:
      - "3014:5000"
    restart: unless-stopped
