version: "3.7"
services:
  source:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      SQL_DATABASE_URL: "postgresql+psycopg2://postgres:100503@my_postgres:5432/Word"
      SECRET_KEY: ${SECRET_KEY}
      TZ: "Asia/Ho_Chi_Minh"
    ports:
      - "3015:5001"
    restart: unless-stopped
    networks:
      - my_network

networks:
  my_network:
    external: true
