version: "3.7"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=100503
      - POSTGRES_DB=Word
  smile-home-backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      SQL_DATABASE_URL: "postgresql+psycopg2://postgres:100503@localhost:5432/Word"
      SECRET_KEY: ${SECRET_KEY}
      TZ: "Asia/Ho_Chi_Minh"
    ports:
      - "3014:5000"
    network_mode: "host"
    restart: unless-stopped
